#!/bin/bash
# get the parent directory of this script
proj_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )

echo "Stopping Beam pipeline..."
beam_pid=$(pgrep -f $proj_dir/build/classes/java/main)
kill -9 $beam_pid > /dev/null 2>&1

echo "Shutting down cbt emulator..."
cbt_pid=$(pgrep -f [g]oogle-cloud-sdk/platform/bigtable-emulator/cbtemulator)
kill -9 $cbt_pid > /dev/null 2>&1

echo "Shutting down pubsub emulator..."
ps_pid=$(pgrep -f [g]oogle-cloud-sdk/platform/pubsub-emulator/lib/cloud-pubsub-emulator)
kill -9 $ps_pid > /dev/null 2>&1

echo "Removing emulator log files..."
rm -f ~/.cbt_emulator.log
rm -f ~/.pubsub_emulator.log

echo "Removing Beam direct runner log file..."
rm -f ~/.beam_direct_runner.log

echo "Cleaning up emulator environment variables..."
unset BIGTABLE_EMULATOR_HOST
unset PUBSUB_EMULATOR_HOST
unset PUBSUB_PROJECT_ID

echo "Done!"